"""first migrate

Revision ID: 35860353503b
Revises: 
Create Date: 2020-04-04 03:16:39.147494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35860353503b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppy',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppy')
    # ### end Alembic commands ###
